"""
Chain Collector Spec Generator
================================
When a new chain crosses the expansion threshold, generates a Claude Code-ready
spec file that contains everything needed to build the collector:
- RPC provider details
- Stablecoin contract addresses on that chain (from CoinGecko)
- The 9 component targets (same as Solana collector)
- The Solana collector as reference implementation
- Protocol list on that chain from the backlog
"""

import os
import logging
from datetime import datetime, timezone

import httpx

logger = logging.getLogger(__name__)

CG_API_KEY = os.environ.get("COINGECKO_API_KEY", "")
CG_BASE = "https://pro-api.coingecko.com/api/v3" if CG_API_KEY else "https://api.coingecko.com/api/v3"

# CoinGecko platform IDs for chains (maps DeFiLlama chain names to CoinGecko asset_platform IDs)
CHAIN_TO_CG_PLATFORM = {
    "Sui": "sui",
    "Aptos": "aptos",
    "Avalanche": "avalanche",
    "BSC": "binance-smart-chain",
    "Polygon": "polygon-pos",
    "Optimism": "optimistic-ethereum",
    "Fantom": "fantom",
    "Tron": "tron",
    "Near": "near-protocol",
    "Cosmos": "cosmos",
}

# Stablecoins to look up on each new chain
TARGET_STABLECOINS = [
    {"symbol": "USDC", "coingecko_id": "usd-coin"},
    {"symbol": "USDT", "coingecko_id": "tether"},
    {"symbol": "DAI", "coingecko_id": "dai"},
    {"symbol": "FDUSD", "coingecko_id": "first-digital-usd"},
    {"symbol": "PYUSD", "coingecko_id": "paypal-usd"},
]


def _get_stablecoin_addresses_on_chain(chain_name: str) -> list:
    """Look up stablecoin contract addresses on a chain via CoinGecko."""
    platform_id = CHAIN_TO_CG_PLATFORM.get(chain_name)
    if not platform_id:
        return []

    results = []
    headers = {"Accept": "application/json"}
    if CG_API_KEY:
        headers["x-cg-pro-api-key"] = CG_API_KEY

    for stable in TARGET_STABLECOINS:
        try:
            resp = httpx.get(
                f"{CG_BASE}/coins/{stable['coingecko_id']}",
                headers=headers,
                params={"localization": "false", "tickers": "false", "market_data": "false"},
                timeout=15,
            )
            if resp.status_code != 200:
                continue

            data = resp.json()
            platforms = data.get("platforms", {})

            if platform_id in platforms and platforms[platform_id]:
                results.append({
                    "symbol": stable["symbol"],
                    "coingecko_id": stable["coingecko_id"],
                    "contract_address": platforms[platform_id],
                    "platform_id": platform_id,
                })
        except Exception as e:
            logger.debug(f"CoinGecko lookup failed for {stable['symbol']} on {chain_name}: {e}")

    return results


def generate_collector_spec(chain_candidate: dict) -> str:
    """
    Generate a Claude Code-ready markdown spec for building a chain collector.

    Args:
        chain_candidate: dict from discover_chain_candidates() with chain, stablecoin_tvl,
                        protocols, stablecoins, rpc_provider

    Returns:
        Path to the generated spec file.
    """
    chain = chain_candidate["chain"]
    rpc = chain_candidate.get("rpc_provider", {})

    # Look up stablecoin addresses on this chain
    stablecoin_addresses = _get_stablecoin_addresses_on_chain(chain)

    # Use the protocols list from the candidate
    chain_protocols = chain_candidate.get("protocols", [])[:15]

    # Read the Solana collector as reference
    solana_collector_path = os.path.join(os.path.dirname(__file__), "..", "collectors", "solana.py")
    try:
        with open(solana_collector_path, "r") as f:
            solana_ref = f.read()
    except Exception:
        solana_ref = "# Could not read solana.py -- check app/collectors/solana.py manually"

    chain_lower = chain.lower()

    # Build the spec
    spec = f"""# Claude Code Prompt: {chain} Chain Collector

## Auto-generated on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
## Generated by: discover_chain_candidates() + generate_collector_spec()

## Why this chain

{chain} has crossed the Basis chain expansion threshold:
- Stablecoin TVL: ${chain_candidate['stablecoin_tvl']/1e6:,.0f}M
- Protocols with stablecoin exposure: {chain_candidate['protocol_count']}
- Stablecoins present: {', '.join(chain_candidate.get('stablecoins', [])[:10])}
- Top protocols: {', '.join(chain_protocols[:10])}

## RPC Provider

- **Provider:** {rpc.get('provider', 'Unknown')}
- **URL:** {rpc.get('url', 'TBD')}
- **Free tier:** {rpc.get('free_tier', 'Check docs')}
- **Env var:** {rpc.get('env_var', chain.upper() + '_RPC_URL')}

## Stablecoin Contract Addresses on {chain}

"""
    if stablecoin_addresses:
        for sa in stablecoin_addresses:
            spec += f"- **{sa['symbol']}**: `{sa['contract_address']}`\n"
    else:
        spec += f"No contract addresses found via CoinGecko for {chain}. Manual lookup needed.\n"

    spec += f"""
## What to Build

Create `app/collectors/{chain_lower}.py` following the same pattern as `app/collectors/solana.py`.

### 9 Target Components (same as Solana)

1. `{chain_lower}_spl_supply` -- total token supply via chain RPC
2. `{chain_lower}_holder_concentration` -- top holder % of supply
3. `{chain_lower}_mint_burn_ratio` -- mint/(mint+burn) from recent transfers
4. `{chain_lower}_daily_mint_volume` -- USD value of mints
5. `{chain_lower}_daily_burn_volume` -- USD value of burns
6. `{chain_lower}_supply_change_velocity` -- abs(net flow / supply) %
7. `{chain_lower}_unusual_minting` -- z-score proxy deviation
8. `{chain_lower}_freeze_authority` -- token freeze/pause capability
9. `{chain_lower}_mint_authority` -- token mint authority status

### Integration Points

1. Add {chain} to `CHAIN_CONFIGS` in `app/indexer/config.py` with stablecoin contract addresses
2. Add {chain} to `SUPPORTED_CHAINS`
3. Wire into worker loop: `safe_collect("{chain_lower}", collect_{chain_lower}_components(client, stablecoin_id))`
4. Add `{rpc.get('env_var', chain.upper() + '_RPC_URL')}` to `app/config.py`
5. Graceful fallback if API key not set

### Chain-Specific Notes

- Check the chain's token standard (SPL for Solana, Coin/FungibleAsset for Sui, etc.)
- Check how to read token supply, holder lists, and transfer history via the chain's RPC
- Check if the chain has a freeze/pause mechanism on tokens
- Rate limiting: respect the RPC provider's free tier limits

## Reference: Solana Collector (app/collectors/solana.py)

```python
{solana_ref}
```

## Protocols to Add to PSI on {chain}

After the collector is built, add these protocols to PSI (same pattern as Drift/Jupiter/Raydium):

"""
    for p in chain_protocols[:10]:
        spec += f"- {p}\n"

    spec += """
## Verification

After building:
1. Set the RPC API key in Replit secrets
2. Trigger a scoring cycle
3. Verify components are collected for stablecoins on this chain
4. Add top protocols to PSI TARGET_PROTOCOLS
5. Trigger PSI scoring and verify
"""

    # Write spec to file
    spec_dir = os.path.join(os.path.dirname(__file__), "..", "..", "docs", "collector_specs")
    os.makedirs(spec_dir, exist_ok=True)

    spec_path = os.path.join(spec_dir, f"{chain_lower}_collector_spec.md")
    with open(spec_path, "w") as f:
        f.write(spec)

    logger.info(f"Chain collector spec generated: {spec_path}")
    return spec_path
