BEGIN;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS tier VARCHAR(20) DEFAULT 'pro';
INSERT INTO migrations (name) VALUES ('019_api_key_email') ON CONFLICT DO NOTHING;
COMMIT;
