"""
Component 2: Analysis generator.

Stage 2a (this stage): builds an AnalysisCreate object with:
  - Real coverage (from app.engine.coverage)
  - Real inputs_hash
  - Stub Signal (empty windowed lists)
  - Stub Interpretation (template:stub)
  - Stub ArtifactRecommendation (recommends "nothing")
  - Empty methodology_observations and follow_ups

Later stages:
  - S2b populates Signal with real observations from covered indexes
  - S2c swaps stub Interpretation for LLM-generated content and populates
    ArtifactRecommendation based on real signal + coverage

This file is the single place where "how is an Analysis assembled" lives.
Every handler that needs to construct one (POST /analyze, later admin
tooling) calls through here.
"""

from __future__ import annotations

import hashlib
import json
from datetime import date, datetime, timezone
from typing import Optional
from uuid import UUID

from app.engine.coverage import get_entity_coverage
from app.engine.schemas import (
    AnalysisCreate,
    ArtifactRecommendation,
    CoverageResponse,
    Interpretation,
    Signal,
)

# Stage stamp on the persisted analysis. Bumped each time the engine's
# behavior shifts so a future reviewer can tell which version produced
# any given row.
ANALYSIS_VERSION_S2A = "v0.1-s2c-llm-interpretation"
# Stub identifiers — used by the skeleton AnalysisCreate that gets INSERTed
# at status=pending. The background task replaces signal/interpretation
# with real values before flipping to draft, so persisted draft rows
# never have these tags.
STUB_PROMPT_VERSION = "stub-s2a"
STUB_MODEL_ID = "template:stub"


# ─────────────────────────────────────────────────────────────────
# inputs_hash
# ─────────────────────────────────────────────────────────────────

def compute_inputs_hash(
    entity: str,
    event_date: Optional[date],
    peer_set: list[str],
    coverage_snapshot_hash: str,
) -> str:
    """Deterministic hash over (entity, event_date, sorted peer_set,
    coverage.data_snapshot_hash). Stored on the Analysis row for
    attestation — a reviewer can recompute it from any Analysis and
    verify the inputs that produced it.

    peer_set is sorted before hashing so peer order doesn't affect the
    hash. coverage_snapshot_hash already encodes the coverage content
    so we don't need to re-hash the coverage here.
    """
    payload = {
        "entity": entity,
        "event_date": event_date.isoformat() if event_date else None,
        "peer_set": sorted(peer_set),
        "coverage_snapshot_hash": coverage_snapshot_hash,
    }
    encoded = json.dumps(payload, sort_keys=True).encode("utf-8")
    return f"sha256:{hashlib.sha256(encoded).hexdigest()}"


# ─────────────────────────────────────────────────────────────────
# Stub components
# ─────────────────────────────────────────────────────────────────

def _stub_signal() -> Signal:
    """Empty signal — used only as a fallback when build_signal can't
    produce anything (no covered indexes have any data in any window).
    Trivially satisfies the AnalysisCreate event-window invariant
    because all four lists are empty.

    S2a used this unconditionally; S2b prefers real observations from
    build_signal and only falls back here if every fetch returns empty.
    """
    return Signal()


def _stub_interpretation(entity: str, inputs_hash: str) -> Interpretation:
    return Interpretation(
        event_summary=(
            f"Stub analysis for {entity}. S2a shipping skeleton; "
            f"S2b and S2c will populate real observations and LLM interpretation."
        ),
        pre_event_story=None,
        event_story=None,
        post_event_story=None,
        cross_peer_reading=None,
        what_this_does_not_claim=(
            "This is a stub from S2a and makes no claims about the entity. "
            "Real analysis requires S2c LLM integration."
        ),
        headline=f"{entity} — stub analysis (S2a skeleton)",
        confidence="insufficient",
        confidence_reasoning=(
            "Stub interpretation generated by S2a endpoint skeleton. "
            "No real analysis performed."
        ),
        prompt_version=STUB_PROMPT_VERSION,
        input_hash=inputs_hash,
        model_id=STUB_MODEL_ID,
        generated_at=datetime.now(timezone.utc),
        from_cache=False,
    )


def _stub_artifact_recommendation() -> ArtifactRecommendation:
    return ArtifactRecommendation(
        recommended="nothing",
        supports=[],
        reasoning=(
            "S2a stub — real recommendation requires S2b observations "
            "and S2c interpretation."
        ),
        blocked=[
            "incident_page",
            "retrospective_internal",
            "case_study",
            "internal_memo",
            "talking_points",
            "one_pager",
        ],
        blocked_reasons=[
            "S2a skeleton produces no usable analysis yet. "
            "Components S2b and S2c must ship before artifacts can be recommended."
        ],
    )


# ─────────────────────────────────────────────────────────────────
# AnalysisCreate assembly
# ─────────────────────────────────────────────────────────────────

def build_stub_analysis(
    entity: str,
    peer_set: list[str],
    event_date: Optional[date],
    context: Optional[str],
    coverage: CoverageResponse,
    previous_analysis_id: Optional[UUID] = None,
    supersedes_reason: Optional[str] = None,
) -> AnalysisCreate:
    """Build the SKELETON AnalysisCreate that gets INSERTed at status=pending.

    Signal and interpretation are stubs at this stage. The background task
    (app.engine.background_tasks.finalize_analysis) replaces them with
    real values asynchronously and then flips status pending → draft.

    This was previously doing the heavy work synchronously, which meant
    POST /api/engine/analyze blocked for ~5–15 seconds on the LLM
    roundtrip — defeating the async pending→draft contract from S2a.
    Restoring the original contract: POST returns 202 in <1s; the
    background task does signal computation + LLM interpretation.

    Function name preserved so analyze_router doesn't change.

    Callers: POST /api/engine/analyze handler. Coverage is fetched once
    by the handler and passed here. No DB reads, no API calls — fast.
    """
    inputs_hash = compute_inputs_hash(
        entity=entity,
        event_date=event_date,
        peer_set=peer_set,
        coverage_snapshot_hash=coverage.data_snapshot_hash,
    )
    return AnalysisCreate(
        analysis_version=ANALYSIS_VERSION_S2A,
        entity=entity,
        event_date=event_date,
        peer_set=peer_set,
        context=context,
        coverage=coverage,
        signal=_stub_signal(),
        interpretation=_stub_interpretation(entity, inputs_hash),
        methodology_observations=[],
        follow_ups=[],
        artifact_recommendation=_stub_artifact_recommendation(),
        inputs_hash=inputs_hash,
        previous_analysis_id=previous_analysis_id,
        supersedes_reason=supersedes_reason,
    )


# ─────────────────────────────────────────────────────────────────
# Coverage lookup adapter
#
# Wraps app.engine.coverage.get_entity_coverage for async handler callers
# via asyncio.to_thread so the sync DB query in coverage.py doesn't block
# the FastAPI event loop.
# ─────────────────────────────────────────────────────────────────

import asyncio


async def fetch_coverage(identifier: str) -> Optional[CoverageResponse]:
    return await asyncio.to_thread(get_entity_coverage, identifier)
