"""
TTI v0.1.0 — Tokenized Treasury Index
=======================================
76 components across 9 categories, measuring risk for tokenized
treasury and real-world asset products.

53% off-chain component ratio — relies heavily on issuer disclosure
ingestion (CDA pattern).
"""

TTI_V01_DEFINITION = {
    "index_id": "tti",
    "version": "v0.1.0",
    "name": "Tokenized Treasury Index",
    "description": "Risk scoring for tokenized treasury and RWA products",
    "entity_type": "tokenized_treasury",
    "categories": {
        "underlying_asset_quality": {"name": "Underlying Asset Quality", "weight": 0.15},
        "reserve_verification": {"name": "Reserve & Collateral Verification", "weight": 0.15},
        "nav_pricing": {"name": "NAV & Pricing Integrity", "weight": 0.10},
        "redemption_liquidity": {"name": "Redemption & Liquidity", "weight": 0.12},
        "smart_contract_infra": {"name": "Smart Contract & Infrastructure", "weight": 0.12},
        "issuer_counterparty": {"name": "Issuer & Counterparty Risk", "weight": 0.12},
        "regulatory_compliance": {"name": "Regulatory & Compliance", "weight": 0.10},
        "holder_distribution": {"name": "Holder & Distribution", "weight": 0.07},
        "market_trading": {"name": "Market & Trading", "weight": 0.07},
    },
    "components": {
        # --- Underlying Asset Quality (15%) ---
        "treasury_duration": {
            "name": "Portfolio Duration",
            "category": "underlying_asset_quality",
            "weight": 0.15,
            "normalization": {"function": "centered", "params": {"center": 1.0, "tolerance": 0.5, "extreme": 3.0}},
            "data_source": "issuer_disclosure",
        },
        "credit_quality": {
            "name": "Credit Quality Score",
            "category": "underlying_asset_quality",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "issuer_disclosure",
        },
        "yield_benchmark_spread": {
            "name": "Yield vs Benchmark Spread (bps)",
            "category": "underlying_asset_quality",
            "weight": 0.10,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 0, "threshold": 100}},
            "data_source": "issuer_disclosure",
        },
        "asset_concentration": {
            "name": "Asset Concentration (%)",
            "category": "underlying_asset_quality",
            "weight": 0.10,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 5, "threshold": 50}},
            "data_source": "issuer_disclosure",
        },
        "sovereign_risk": {
            "name": "Sovereign Risk Score",
            "category": "underlying_asset_quality",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "maturity_profile": {
            "name": "Maturity Profile Score",
            "category": "underlying_asset_quality",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "issuer_disclosure",
        },
        "interest_rate_sensitivity": {
            "name": "Interest Rate Sensitivity",
            "category": "underlying_asset_quality",
            "weight": 0.10,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 0, "threshold": 5}},
            "data_source": "issuer_disclosure",
        },
        "liquidity_of_underlying": {
            "name": "Underlying Asset Liquidity Score",
            "category": "underlying_asset_quality",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "currency_risk": {
            "name": "Currency Risk Score",
            "category": "underlying_asset_quality",
            "weight": 0.05,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "reinvestment_risk": {
            "name": "Reinvestment Risk Score",
            "category": "underlying_asset_quality",
            "weight": 0.05,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },

        # --- Reserve & Collateral Verification (15%) ---
        "attestation_frequency": {
            "name": "Attestation Frequency Score",
            "category": "reserve_verification",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "issuer_disclosure",
        },
        "attestation_recency_days": {
            "name": "Attestation Recency (days)",
            "category": "reserve_verification",
            "weight": 0.12,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 0, "threshold": 90}},
            "data_source": "issuer_disclosure",
        },
        "auditor_quality": {
            "name": "Auditor Quality Score",
            "category": "reserve_verification",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "reserve_coverage_ratio": {
            "name": "Reserve Coverage Ratio (%)",
            "category": "reserve_verification",
            "weight": 0.12,
            "normalization": {"function": "linear", "params": {"min_val": 95, "max_val": 105}},
            "data_source": "issuer_disclosure",
        },
        "collateral_segregation": {
            "name": "Collateral Segregation Score",
            "category": "reserve_verification",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "custodian_quality": {
            "name": "Custodian Quality Score",
            "category": "reserve_verification",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "onchain_verification": {
            "name": "On-Chain Verification Score",
            "category": "reserve_verification",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "etherscan",
        },
        "bankruptcy_remoteness": {
            "name": "Bankruptcy Remoteness Score",
            "category": "reserve_verification",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "rehypothecation_risk": {
            "name": "Rehypothecation Risk Score",
            "category": "reserve_verification",
            "weight": 0.05,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "collateral_composition_disclosure": {
            "name": "Collateral Composition Disclosure Score",
            "category": "reserve_verification",
            "weight": 0.04,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "issuer_disclosure",
        },

        # --- NAV & Pricing Integrity (10%) ---
        "nav_deviation": {
            "name": "NAV Deviation from Par (%)",
            "category": "nav_pricing",
            "weight": 0.20,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 0, "threshold": 3}},
            "data_source": "issuer_disclosure",
        },
        "nav_update_frequency": {
            "name": "NAV Update Frequency Score",
            "category": "nav_pricing",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "issuer_disclosure",
        },
        "pricing_methodology": {
            "name": "Pricing Methodology Score",
            "category": "nav_pricing",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "oracle_integration": {
            "name": "Oracle Integration Score",
            "category": "nav_pricing",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "nav_volatility_30d": {
            "name": "NAV 30d Volatility (%)",
            "category": "nav_pricing",
            "weight": 0.10,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 0, "threshold": 2}},
            "data_source": "issuer_disclosure",
        },
        "mark_to_market_accuracy": {
            "name": "Mark-to-Market Accuracy Score",
            "category": "nav_pricing",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "pricing_source_diversity": {
            "name": "Pricing Source Diversity Score",
            "category": "nav_pricing",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "accrual_mechanism": {
            "name": "Accrual Mechanism Score",
            "category": "nav_pricing",
            "weight": 0.05,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },

        # --- Redemption & Liquidity (12%) ---
        "redemption_window": {
            "name": "Redemption Window Score",
            "category": "redemption_liquidity",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "settlement_time_hours": {
            "name": "Settlement Time (hours)",
            "category": "redemption_liquidity",
            "weight": 0.12,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 0, "threshold": 72}},
            "data_source": "config",
        },
        "min_redemption_amount": {
            "name": "Minimum Redemption Amount Score",
            "category": "redemption_liquidity",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "tti_tvl": {
            "name": "Product TVL (USD)",
            "category": "redemption_liquidity",
            "weight": 0.12,
            "normalization": {"function": "log", "params": {"thresholds": {1000000: 10, 10000000: 30, 100000000: 60, 500000000: 80, 1000000000: 100}}},
            "data_source": "defillama",
        },
        "secondary_market_liquidity": {
            "name": "Secondary Market Liquidity Score",
            "category": "redemption_liquidity",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "defillama",
        },
        "gate_mechanism": {
            "name": "Gate/Suspension Mechanism Score",
            "category": "redemption_liquidity",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "redemption_fee": {
            "name": "Redemption Fee Score",
            "category": "redemption_liquidity",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "instant_liquidity_pct": {
            "name": "Instant Liquidity % of TVL",
            "category": "redemption_liquidity",
            "weight": 0.10,
            "normalization": {"function": "linear", "params": {"min_val": 5, "max_val": 50}},
            "data_source": "config",
        },
        "queue_depth": {
            "name": "Redemption Queue Depth Score",
            "category": "redemption_liquidity",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "cross_chain_availability": {
            "name": "Cross-Chain Availability Score",
            "category": "redemption_liquidity",
            "weight": 0.05,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "defillama",
        },

        # --- Smart Contract & Infrastructure (12%) ---
        "tti_contract_audit": {
            "name": "Contract Audit Score",
            "category": "smart_contract_infra",
            "weight": 0.12,
            "normalization": {"function": "log", "params": {"thresholds": {1: 30, 2: 50, 3: 70, 5: 85, 10: 100}}},
            "data_source": "config",
        },
        "tti_upgradeability": {
            "name": "Upgradeability Risk Score",
            "category": "smart_contract_infra",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "tti_admin_key_risk": {
            "name": "Admin Key Risk Score",
            "category": "smart_contract_infra",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "access_control": {
            "name": "Access Control Score",
            "category": "smart_contract_infra",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "compliance_module": {
            "name": "Compliance Module Score",
            "category": "smart_contract_infra",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "oracle_dependency": {
            "name": "Oracle Dependency Score",
            "category": "smart_contract_infra",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "tti_contract_age_days": {
            "name": "Contract Age (days)",
            "category": "smart_contract_infra",
            "weight": 0.08,
            "normalization": {"function": "log", "params": {"thresholds": {30: 10, 90: 30, 180: 50, 365: 70, 730: 100}}},
            "data_source": "etherscan",
        },
        "chain_infrastructure": {
            "name": "Chain Infrastructure Score",
            "category": "smart_contract_infra",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "tti_bug_bounty": {
            "name": "Bug Bounty Score",
            "category": "smart_contract_infra",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "minting_mechanism": {
            "name": "Minting/Burning Mechanism Score",
            "category": "smart_contract_infra",
            "weight": 0.08,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "emergency_mechanism": {
            "name": "Emergency Mechanism Score",
            "category": "smart_contract_infra",
            "weight": 0.06,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "dependency_risk": {
            "name": "Dependency Risk Score",
            "category": "smart_contract_infra",
            "weight": 0.06,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },

        # --- Issuer & Counterparty Risk (12%) ---
        "issuer_regulatory_status": {
            "name": "Issuer Regulatory Status Score",
            "category": "issuer_counterparty",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "issuer_track_record": {
            "name": "Issuer Track Record Score",
            "category": "issuer_counterparty",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "issuer_aum": {
            "name": "Issuer AUM (USD)",
            "category": "issuer_counterparty",
            "weight": 0.12,
            "normalization": {"function": "log", "params": {"thresholds": {10000000: 20, 100000000: 40, 1000000000: 60, 10000000000: 80, 100000000000: 100}}},
            "data_source": "config",
        },
        "counterparty_count": {
            "name": "Counterparty Diversification",
            "category": "issuer_counterparty",
            "weight": 0.10,
            "normalization": {"function": "log", "params": {"thresholds": {1: 20, 2: 40, 3: 60, 5: 80, 10: 100}}},
            "data_source": "config",
        },
        "bank_partner_quality": {
            "name": "Bank Partner Quality Score",
            "category": "issuer_counterparty",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "insurance_coverage_tti": {
            "name": "Insurance Coverage Score",
            "category": "issuer_counterparty",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "conflict_of_interest": {
            "name": "Conflict of Interest Score",
            "category": "issuer_counterparty",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "operational_continuity_tti": {
            "name": "Operational Continuity Score",
            "category": "issuer_counterparty",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "key_person_risk": {
            "name": "Key Person Risk Score",
            "category": "issuer_counterparty",
            "weight": 0.11,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },

        # --- Regulatory & Compliance (10%) ---
        "securities_registration": {
            "name": "Securities Registration Score",
            "category": "regulatory_compliance",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "investor_accreditation": {
            "name": "Investor Accreditation Score",
            "category": "regulatory_compliance",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "kyc_aml_compliance": {
            "name": "KYC/AML Compliance Score",
            "category": "regulatory_compliance",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "transfer_restrictions": {
            "name": "Transfer Restrictions Score",
            "category": "regulatory_compliance",
            "weight": 0.10,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "tax_reporting": {
            "name": "Tax Reporting Score",
            "category": "regulatory_compliance",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "prospectus_availability": {
            "name": "Prospectus Availability Score",
            "category": "regulatory_compliance",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "jurisdiction_risk_tti": {
            "name": "Jurisdiction Risk Score",
            "category": "regulatory_compliance",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "regulatory_change_risk": {
            "name": "Regulatory Change Risk Score",
            "category": "regulatory_compliance",
            "weight": 0.12,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },

        # --- Holder & Distribution (7%) ---
        "tti_holder_count": {
            "name": "Holder Count",
            "category": "holder_distribution",
            "weight": 0.20,
            "normalization": {"function": "log", "params": {"thresholds": {10: 10, 50: 30, 200: 50, 1000: 70, 5000: 100}}},
            "data_source": "etherscan",
        },
        "tti_top10_concentration": {
            "name": "Top 10 Holder Concentration (%)",
            "category": "holder_distribution",
            "weight": 0.20,
            "normalization": {"function": "inverse_linear", "params": {"perfect": 20, "threshold": 95}},
            "data_source": "etherscan",
        },
        "institutional_holder_pct": {
            "name": "Institutional Holder %",
            "category": "holder_distribution",
            "weight": 0.15,
            "normalization": {"function": "linear", "params": {"min_val": 10, "max_val": 80}},
            "data_source": "config",
        },
        "defi_integration_count": {
            "name": "DeFi Integration Count",
            "category": "holder_distribution",
            "weight": 0.15,
            "normalization": {"function": "log", "params": {"thresholds": {1: 20, 3: 40, 5: 60, 10: 80, 20: 100}}},
            "data_source": "defillama",
        },
        "geographic_distribution": {
            "name": "Geographic Distribution Score",
            "category": "holder_distribution",
            "weight": 0.15,
            "normalization": {"function": "direct", "params": {}},
            "data_source": "config",
        },
        "holder_growth_rate": {
            "name": "Holder Growth Rate (30d %)",
            "category": "holder_distribution",
            "weight": 0.15,
            "normalization": {"function": "centered", "params": {"center": 5, "tolerance": 5, "extreme": 30}},
            "data_source": "etherscan",
        },

        # --- Market & Trading (7%) ---
        "tti_volume_24h": {
            "name": "24h Trading Volume (USD)",
            "category": "market_trading",
            "weight": 0.40,
            "normalization": {"function": "log", "params": {"thresholds": {10000: 10, 100000: 30, 1000000: 50, 10000000: 70, 100000000: 100}}},
            "data_source": "coingecko",
        },
        "tti_market_cap": {
            "name": "Market Cap (USD)",
            "category": "market_trading",
            "weight": 0.35,
            "normalization": {"function": "log", "params": {"thresholds": {1000000: 10, 10000000: 30, 100000000: 60, 500000000: 80, 1000000000: 100}}},
            "data_source": "coingecko",
        },
        "exchange_listing_count": {
            "name": "Exchange Listing Count",
            "category": "market_trading",
            "weight": 0.25,
            "normalization": {"function": "log", "params": {"thresholds": {1: 20, 3: 40, 5: 60, 10: 80, 20: 100}}},
            "data_source": "coingecko",
        },
    },
}

TTI_ENTITIES = [
    {"slug": "ondo-ousg", "name": "Ondo OUSG", "issuer": "Ondo Finance", "coingecko_id": "ondo-us-dollar-yield"},
    {"slug": "ondo-usdy", "name": "Ondo USDY", "issuer": "Ondo Finance", "coingecko_id": "ondo-usd-yield"},
    {"slug": "blackrock-buidl", "name": "BlackRock BUIDL", "issuer": "BlackRock", "coingecko_id": "build-on-bitcoin"},
    {"slug": "franklin-benji", "name": "Franklin BENJI", "issuer": "Franklin Templeton", "coingecko_id": "franklin-templeton-benji-investments"},
    {"slug": "backed-bib01", "name": "Backed bIB01", "issuer": "Backed Finance", "coingecko_id": None},
    {"slug": "maple-cash", "name": "Maple Cash Management", "issuer": "Maple Finance", "coingecko_id": "maple"},
    {"slug": "centrifuge-pools", "name": "Centrifuge Pools", "issuer": "Centrifuge", "coingecko_id": "centrifuge"},
    {"slug": "superstate-ustb", "name": "Superstate USTB", "issuer": "Superstate", "coingecko_id": None},
    {"slug": "mountain-usdm", "name": "Mountain USDM", "issuer": "Mountain Protocol", "coingecko_id": "mountain-protocol-usdm"},
    {"slug": "openeden-tbill", "name": "OpenEden TBILL", "issuer": "OpenEden", "coingecko_id": None},
]
